int rgb = 0;
int alpha = 1;
int MODE = rgb;

PImage img;

void setup() { //initializes a new image using RGB
  size(800, 947);
  img = createImage(width, height, ARGB);
  img.loadPixels();
}

void draw() {// Creates a white background, and creates text 
  background(255);
  fill(160, 32, 240); //turns text to blue (or desired) color
  textSize(30);
  textAlign(CENTER, CENTER);
  text("GENERATED BY GENERATOR", width/2, height/2);
  img = get(); // returns the entire image 
  image(img, 0, 0);
  save("generated.png");
  noLoop();
}
