int rgb = 0;
int alpha = 1;
int MODE = rgb;

PImage img;

void setup() { //initializes a new image using RGB
  size(800, 947);
  img = createImage(width, height, ARGB);
  img.loadPixels();
}

void draw() {
  background(255); // white background
  fill(160, 32, 240); // text color
  textSize(30);
  textAlign(CENTER, CENTER);
  text("this was generated by generator", width/2, height/2);
  img = get(); // returns the entire image 
  image(img, 0, 0);
  save("generated.png");
  noLoop();
}
